export interface SubtitleSegment {
  id: string;
  start: number; // in seconds
  end: number;   // in seconds
  text: string;
}

/**
 * Format seconds into HH:MM:SS,mmm (SRT) or HH:MM:SS.mmm (VTT)
 */
export function formatTime(seconds: number, format: 'srt' | 'vtt' = 'srt'): string {
  if (isNaN(seconds) || seconds < 0) seconds = 0;
  
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const millis = Math.floor((seconds - Math.floor(seconds)) * 1000);

  const pad = (n: number, z = 2) => n.toString().padStart(z, '0');
  const separator = format === 'srt' ? ',' : '.';

  return `${pad(hrs)}:${pad(mins)}:${pad(secs)}${separator}${pad(millis, 3)}`;
}

/**
 * Parse an SRT / VTT timestamp string into seconds
 */
export function parseTime(timeStr: string): number {
  if (!timeStr) return 0;
  const cleaned = timeStr.trim().replace(',', '.');
  const parts = cleaned.split(':');
  
  let hours = 0;
  let minutes = 0;
  let seconds = 0;

  if (parts.length === 3) {
    hours = parseFloat(parts[0]) || 0;
    minutes = parseFloat(parts[1]) || 0;
    seconds = parseFloat(parts[2]) || 0;
  } else if (parts.length === 2) {
    minutes = parseFloat(parts[0]) || 0;
    seconds = parseFloat(parts[1]) || 0;
  } else if (parts.length === 1) {
    seconds = parseFloat(parts[0]) || 0;
  }

  return hours * 3600 + minutes * 60 + seconds;
}

/**
 * Generate standard SubRip (.SRT) text
 */
export function generateSrt(segments: SubtitleSegment[]): string {
  return segments
    .filter(seg => seg.text && seg.text.trim().length > 0)
    .sort((a, b) => a.start - b.start)
    .map((seg, index) => {
      const idx = index + 1;
      const start = formatTime(seg.start, 'srt');
      const end = formatTime(Math.max(seg.end, seg.start + 0.1), 'srt');
      return `${idx}\n${start} --> ${end}\n${seg.text.trim()}\n`;
    })
    .join('\n');
}

/**
 * Generate standard WebVTT (.VTT) text
 */
export function generateVtt(segments: SubtitleSegment[]): string {
  const body = segments
    .filter(seg => seg.text && seg.text.trim().length > 0)
    .sort((a, b) => a.start - b.start)
    .map((seg, index) => {
      const idx = index + 1;
      const start = formatTime(seg.start, 'vtt');
      const end = formatTime(Math.max(seg.end, seg.start + 0.1), 'vtt');
      return `${idx}\n${start} --> ${end}\n${seg.text.trim()}\n`;
    })
    .join('\n');

  return `WEBVTT - Generated by CaptionLK\n\n${body}`;
}

/**
 * Generate plain text transcript (.TXT)
 */
export function generateTxt(segments: SubtitleSegment[]): string {
  return segments
    .filter(seg => seg.text && seg.text.trim().length > 0)
    .sort((a, b) => a.start - b.start)
    .map(seg => seg.text.trim())
    .join('\n');
}

/**
 * Generate JSON export
 */
export function generateJson(segments: SubtitleSegment[], metadata: Record<string, any> = {}): string {
  return JSON.stringify(
    {
      generator: 'CaptionLK (https://captionlk.github.io)',
      exportedAt: new Date().toISOString(),
      metadata,
      subtitles: segments.map(seg => ({
        id: seg.id,
        start: seg.start,
        end: seg.end,
        startTimeFormatted: formatTime(seg.start, 'srt'),
        endTimeFormatted: formatTime(seg.end, 'srt'),
        text: seg.text.trim()
      }))
    },
    null,
    2
  );
}

/**
 * Trigger download of any text file via Blob
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
